# Generated by Django 4.2.2 on 2023-06-25 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_order_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminprofile',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='adminprofile',
            name='role',
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='surname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
