# Generated by Django 4.2.2 on 2023-06-28 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('Chocolate Candy', 'Chocolate Candy'), ('Cotton Candy', 'Cotton Candy'), ('Chewing Gum', 'Chewing Gum'), ('Lollipop', 'Lollipop'), ('Hard Candy', 'Hard Candy'), ('Gummy Candy', 'Gummy Candy')], max_length=50),
        ),
    ]
